version=${project.version}
buildtime=${timestamp}
builder=${env.USERNAME}
builderName=${time.build.user.name}
builderEmail=${time.build.user.email}
buildhost=${env.COMPUTERNAME}
buildOs=${os.name}
gitBranch=${time.branch}
gitCommitIdDescribe=${time.commit.id.describe}
gitCommitId=${time.commit.id.full}
gitCommitUrl=${time.remote.origin.url}
gitCommitTime=${time.commit.time}
gitDirty=${time.dirty}